In [2]:
import pandas as pd
from datetime import timedelta
import json
import warnings
import numpy as np
# Suppress all warnings
warnings.filterwarnings("ignore")

# Your code that generates warnings

In [3]:
Spo_dict = {
        "name": [
            "SPO 07.12 TO 15.12 (1)",
            "SPO 07.12 TO 15.12 (2)",
            "SPO 18.12 TO 31.01",
            "spo 01.03 to 07.03",
            "SPO 14.03 TO 31.03(1)",
            "SPO 14.03 TO 31.03 (2)",
            "SPO 01.04 TO 15.04",
            "SPO 01.04 TO 15.04 (2)",
            "SPO 16.04 TO 27.04",
            "SPO 28.04 TO 05.05 ",
            "SPO 06.05 TO 27.05",
            "SPO 28.05 TO 15.06",
            "SPO 16.06 TO 05.07",
            "SPO 06.07 TO 31.07",
            "spo 01.08 to 15.08"
        ],
        "start_date": [
            "2022-12-07 00:00:00",
            "2022-12-07 00:00:00",
            "2022-12-18 00:00:00",
            "2023-03-01 00:00:00",
            "2023-03-14 00:00:00",
            "2023-03-14 00:00:00",
            "2023-04-01 00:00:00",
            "2023-04-01 00:00:00",
            "2023-04-16 00:00:00",
            "2023-05-01 00:00:00",
            "2023-05-06 00:00:00",
            "2023-05-28 00:00:00",
            "2023-06-16 00:00:00",
            "2023-07-06 00:00:00",
            "2023-08-01 00:00:00"
        ],
        "end_date": [
            "2022-12-15 00:00:00",
            "2022-12-15 00:00:00",
            "2023-01-31 00:00:00",
            "2023-03-07 00:00:00",
            "2023-03-31 00:00:00",
            "2023-03-31 00:00:00",
            "2023-04-15 00:00:00",
            "2023-04-15 00:00:00",
            "2023-04-30 00:00:00",
            "2023-05-05 00:00:00",
            "2023-05-27 00:00:00",
            "2023-06-15 00:00:00",
            "2023-07-05 00:00:00",
            "2023-07-31 00:00:00",
            "2023-08-15 00:00:00"
        ]
}

In [4]:
def date_between(date1, start_date, end_date):
    # Check if date1 is between start_date and end_date
    result = ((date1 >= start_date) & (date1 <= end_date))
    return result

In [5]:
file_path = r"D:\vscoded\Credit_App\TEST FILES\da.sep..xlsx"
statment = pd.read_excel(file_path,sheet_name='statment')
con = pd.read_excel(file_path,sheet_name= "contract")
statment = statment.dropna(subset=['Arrival'])

In [6]:
end_date_np = np.array(Spo_dict['end_date'], dtype='datetime64').reshape(-1,1)
start_date_np = np.array(Spo_dict['start_date'], dtype='datetime64').reshape(-1,1)


result = np.vectorize(date_between)(statment['Res_date'],start_date_np,end_date_np).T

In [7]:
result.shape

(21, 15)

In [9]:
invoices = np.array(list(pd.read_excel(file_path,sheet_name= Spo_dict['name']).values())[:2])

In [12]:
invoices

array([[[Timestamp('2023-05-01 00:00:00'),
         Timestamp('2023-05-15 00:00:00'), 85.7375, 90.25,
         94.76249999999999, 108.3, 135.375, 77.615, 150.040625,
         157.9375, 165.83437499999997, 189.525, 171.475, 180.5,
         189.52499999999998, 216.6, 270.75, 155.23, 240.06499999999997,
         265.335, 303.23999999999995, 379.04999999999995,
         217.32199999999997, 487.35, 236.90624999999997, 270.75,
         338.4375],
        [Timestamp('2023-05-16 00:00:00'),
         Timestamp('2023-06-30 00:00:00'), 81.225, 85.7375, 90.25,
         103.7875, 129.05749999999998, 73.1025, 142.14374999999998,
         150.040625, 157.9375, 181.62812499999998, 162.45, 171.475,
         180.5, 207.575, 258.11499999999995, 146.205,
         227.42999999999998, 252.7, 290.60499999999996,
         361.36099999999993, 204.687, 464.6069999999999, 225.625,
         259.46875, 322.64374999999995]],

       [[Timestamp('2023-09-01 00:00:00'),
         Timestamp('2023-09-30 00:00:00'), 85.7375, 90.25,
         94.76249999999999, 108.3, 135.375, 77.615, 150.040625,
         157.9375, 165.83437499999997, 189.525, 171.475, 180.5,
         189.52499999999998, 216.6, 270.75, 155.23, 240.06499999999997,
         265.335, 303.23999999999995, 379.04999999999995,
         217.32199999999997, 487.35, 236.90624999999997, 270.75,
         338.4375],
        [Timestamp('2023-10-01 00:00:00'),
         Timestamp('2023-10-31 00:00:00'), 90.25, 94.76249999999999,
         99.27499999999999, 112.8125, 142.595, 81.225, 157.9375,
         165.83437499999997, 173.73125, 197.421875, 180.5,
         189.52499999999998, 198.54999999999998, 225.625, 285.19,
         162.45, 252.7, 277.96999999999997, 315.875, 399.26599999999996,
         227.42999999999998, 513.342, 248.18749999999997, 282.03125,
         356.4875]]], dtype=object)

In [11]:
try:
    invoices = np.array(list(pd.read_excel(file_path,sheet_name= Spo_dict['name']).values()))
except ValueError:
    # Handle the case where the worksheet is not found
    print("Worksheet not found")

Worksheet not found

In [13]:
def invoice_optimizer(cell,invoice):
    
    begin_date = invoice['first date'].iloc[0]
    end_date = invoice['second date'].iloc[-1]
    
    arr = cell['Arrival']
    dep = cell['Departure'] - timedelta(1)
    code = cell['Rate code']

    if begin_date > arr:
        arr = begin_date
    if end_date < dep:
        dep = end_date
    
    date_range = con[(arr<=con["second date"]) & (dep>=con["first date"])]
    empty_df = date_range.empty
    
    days = 0 
    price = 0
    
    if not empty_df:
        date_range['first date'].iloc[0] = arr
        date_range['second date'].iloc[-1] = dep
        
        days = np.array((date_range['second date'] - date_range['first date']).dt.days + 1)
        price = np.array(date_range[cell['Rate code']])
        
    return days, price, arr, dep, empty_df

In [14]:
dict_of_rows = np.array(statment.to_dict(orient='records')).reshape(-1,1)

In [15]:
invoice_tuple = np.vectorize(invoice_optimizer)(dict_of_rows,invoices)

TypeError: 'Timestamp' object is not subscriptable

In [194]:
def contract_removal(date1,date2,cell,right_spo,empty_df):
    if (right_spo) and not(empty_df):
        arr = cell['Arrival']
        dep = cell['Departure'] - timedelta(1)
        code = cell['Rate code']
        
        con1 = con[(arr<=con["second date"]) & (date1>=con["first date"])]
        con2 = con[(date2<=con["second date"]) & (dep>=con["first date"])]
        
        con1['first date'].iloc[0] = arr
        con1['second date'].iloc[-1] = date1
        
        
        con2['first date'].iloc[0] = date2
        con2['second date'].iloc[-1] = dep
        
        result = pd.concat([con1, con2], axis=0)

        
        empty_df = result.empty
    else:
        arr = cell['Arrival']
        dep = cell['Departure'] - timedelta(1)
        code = cell['Rate code']
        
        date_range = con[(arr<=con["second date"]) & (dep>=con["first date"])]
        date_range['first date'].iloc[0] = arr
        date_range['second date'].iloc[-1] = date1
        return date_range
    return result

In [196]:
invoice_tuple[4]

array([[ True,  True,  True, False, False, False],
       [ True,  True,  True, False, False, False],
       [ True,  True,  True, False, False, False],
       [ True,  True,  True, False, False, False]])

In [198]:
np.vectorize(contract_removal)(invoice_tuple[2],invoice_tuple[3],dict_of_rows,result,invoice_tuple[4])

True
True
True
True
False
False
False
True
True
True
False
False
False
True
True
True
False
False
False
True
True
True
False
False
False

array([[  first date second date  Main Rate D.STD.GV  Main Rate D.STD.PV  \
        3 2023-07-15  2023-07-15                95.0               99.75

           Main Rate D.SUP.PV  Main Rate D.SUP.SV  Main Rate FAM- PV  Main Rate D.ECO  \
        3               104.5              118.75              150.1             85.5

           SGL - STD - GV  SGL - STD - PV  ...  DBL - ECO  TPL - STD - GV  \
        3          166.25        174.5625  ...      171.0           266.0

           TPL - SUP - PV  TPL - SUP - SV  TPL - FAM - PV  TPL - ECO  QAD - FAM - PV  \
        3           292.6           332.5          420.28      239.4          540.36

           DBL - SUP - PV +2CH  DBL - SUP - SV +2CH  DBL - FAM - PV+2CH
        3               261.25              296.875              375.25

        [1 rows x 27 columns]                                                           ,
          first date second date  Main Rate D.STD.GV  Main Rate D.STD.PV  \
        3 2023-07-15  2023-09-01                95.0               99.75

           Main Rate D.SUP.PV  Main Rate D.SUP.SV  Main Rate FAM- PV  Main Rate D.ECO  \
        3               104.5              118.75              150.1             85.5

           SGL - STD - GV  SGL - STD - PV  ...  DBL - ECO  TPL - STD - GV  \
        3          166.25        174.5625  ...      171.0           266.0

           TPL - SUP - PV  TPL - SUP - SV  TPL - FAM - PV  TPL - ECO  QAD - FAM - PV  \
        3           292.6           332.5          420.28      239.4          540.36

           DBL - SUP - PV +2CH  DBL - SUP - SV +2CH  DBL - FAM - PV+2CH
        3               261.25              296.875              375.25

        [1 rows x 27 columns]                                                           ,
          first date second date  Main Rate D.STD.GV  Main Rate D.STD.PV  \
        3 2023-07-15  2023-07-15                95.0               99.75

           Main Rate D.SUP.PV  Main Rate D.SUP.SV  Main Rate FAM- PV  Main Rate D.ECO  \
        3               104.5              118.75              150.1             85.5

           SGL - STD - GV  SGL - STD - PV  ...  DBL - ECO  TPL - STD - GV  \
        3          166.25        174.5625  ...      171.0           266.0

           TPL - SUP - PV  TPL - SUP - SV  TPL - FAM - PV  TPL - ECO  QAD - FAM - PV  \
        3           292.6           332.5          420.28      239.4          540.36

           DBL - SUP - PV +2CH  DBL - SUP - SV +2CH  DBL - FAM - PV+2CH
        3               261.25              296.875              375.25

        [1 rows x 27 columns]                                                           ,
          first date second date  Main Rate D.STD.GV  Main Rate D.STD.PV  \
        3 2023-07-15  2023-07-15                95.0               99.75

           Main Rate D.SUP.PV  Main Rate D.SUP.SV  Main Rate FAM- PV  Main Rate D.ECO  \
        3               104.5              118.75              150.1             85.5

           SGL - STD - GV  SGL - STD - PV  ...  DBL - ECO  TPL - STD - GV  \
        3          166.25        174.5625  ...      171.0           266.0

           TPL - SUP - PV  TPL - SUP - SV  TPL - FAM - PV  TPL - ECO  QAD - FAM - PV  \
        3           292.6           332.5          420.28      239.4          540.36

           DBL - SUP - PV +2CH  DBL - SUP - SV +2CH  DBL - FAM - PV+2CH
        3               261.25              296.875              375.25

        [1 rows x 27 columns]                                                           ,
          first date second date  Main Rate D.STD.GV  Main Rate D.STD.PV  \
        3 2023-07-15  2023-07-15                95.0               99.75

           Main Rate D.SUP.PV  Main Rate D.SUP.SV  Main Rate FAM- PV  Main Rate D.ECO  \
        3               104.5              118.75              150.1             85.5

           SGL - STD - GV  SGL - STD - PV  ...  DBL - ECO  TPL - STD - GV  \
        3          166.25        174.5625  ...      171.0           266.0

           TPL - SUP - PV  TPL - SUP - SV  TPL - FAM - PV  TPL - ECO  QAD - FAM - PV  \
        3           292.6           332.5          420.28      239.4          540.36

           DBL - SUP - PV +2CH  DBL - SUP - SV +2CH  DBL - FAM - PV+2CH
        3               261.25              296.875              375.25

        [1 rows x 27 columns]                                                           ,
          first date second date  Main Rate D.STD.GV  Main Rate D.STD.PV  \
        3 2023-07-15  2023-07-15                95.0               99.75

           Main Rate D.SUP.PV  Main Rate D.SUP.SV  Main Rate FAM- PV  Main Rate D.ECO  \
        3               104.5              118.75              150.1             85.5

           SGL - STD - GV  SGL - STD - PV  ...  DBL - ECO  TPL - STD - GV  \
        3          166.25        174.5625  ...      171.0           266.0

           TPL - SUP - PV  TPL - SUP - SV  TPL - FAM - PV  TPL - ECO  QAD - FAM - PV  \
        3           292.6           332.5          420.28      239.4          540.36

           DBL - SUP - PV +2CH  DBL - SUP - SV +2CH  DBL - FAM - PV+2CH
        3               261.25              296.875              375.25

        [1 rows x 27 columns]                                                           ],
       [  first date second date  Main Rate D.STD.GV  Main Rate D.STD.PV  \
        2 2023-07-04  2023-07-04               90.25                95.0

           Main Rate D.SUP.PV  Main Rate D.SUP.SV  Main Rate FAM- PV  Main Rate D.ECO  \
        2               99.75               114.0              142.5             81.7

           SGL - STD - GV  SGL - STD - PV  ...  DBL - ECO  TPL - STD - GV  \
        2        157.9375          166.25  ...      163.4           252.7

           TPL - SUP - PV  TPL - SUP - SV  TPL - FAM - PV  TPL - ECO  QAD - FAM - PV  \
        2           279.3           319.2           399.0     228.76           513.0

           DBL - SUP - PV +2CH  DBL - SUP - SV +2CH  DBL - FAM - PV+2CH
        2              249.375                285.0              356.25

        [1 rows x 27 columns]                                                           ,
          first date second date  Main Rate D.STD.GV  Main Rate D.STD.PV  \
        2 2023-07-04  2023-09-01               90.25                95.0

           Main Rate D.SUP.PV  Main Rate D.SUP.SV  Main Rate FAM- PV  Main Rate D.ECO  \
        2               99.75               114.0              142.5             81.7

           SGL - STD - GV  SGL - STD - PV  ...  DBL - ECO  TPL - STD - GV  \
        2        157.9375          166.25  ...      163.4           252.7

           TPL - SUP - PV  TPL - SUP - SV  TPL - FAM - PV  TPL - ECO  QAD - FAM - PV  \
        2           279.3           319.2           399.0     228.76           513.0

           DBL - SUP - PV +2CH  DBL - SUP - SV +2CH  DBL - FAM - PV+2CH
        2              249.375                285.0              356.25

        [1 rows x 27 columns]                                                           ,
          first date second date  Main Rate D.STD.GV  Main Rate D.STD.PV  \
        2 2023-07-04  2023-07-04               90.25                95.0

           Main Rate D.SUP.PV  Main Rate D.SUP.SV  Main Rate FAM- PV  Main Rate D.ECO  \
        2               99.75               114.0              142.5             81.7

           SGL - STD - GV  SGL - STD - PV  ...  DBL - ECO  TPL - STD - GV  \
        2        157.9375          166.25  ...      163.4           252.7

           TPL - SUP - PV  TPL - SUP - SV  TPL - FAM - PV  TPL - ECO  QAD - FAM - PV  \
        2           279.3           319.2           399.0     228.76           513.0

           DBL - SUP - PV +2CH  DBL - SUP - SV +2CH  DBL - FAM - PV+2CH
        2              249.375                285.0              356.25

        [1 rows x 27 columns]                                                           ,
          first date second date  Main Rate D.STD.GV  Main Rate D.STD.PV  \
        2 2023-07-04  2023-07-04               90.25                95.0

           Main Rate D.SUP.PV  Main Rate D.SUP.SV  Main Rate FAM- PV  Main Rate D.ECO  \
        2               99.75               114.0              142.5             81.7

           SGL - STD - GV  SGL - STD - PV  ...  DBL - ECO  TPL - STD - GV  \
        2        157.9375          166.25  ...      163.4           252.7

           TPL - SUP - PV  TPL - SUP - SV  TPL - FAM - PV  TPL - ECO  QAD - FAM - PV  \
        2           279.3           319.2           399.0     228.76           513.0

           DBL - SUP - PV +2CH  DBL - SUP - SV +2CH  DBL - FAM - PV+2CH
        2              249.375                285.0              356.25

        [1 rows x 27 columns]                                                           ,
          first date second date  Main Rate D.STD.GV  Main Rate D.STD.PV  \
        2 2023-07-04  2023-07-04               90.25                95.0

           Main Rate D.SUP.PV  Main Rate D.SUP.SV  Main Rate FAM- PV  Main Rate D.ECO  \
        2               99.75               114.0              142.5             81.7

           SGL - STD - GV  SGL - STD - PV  ...  DBL - ECO  TPL - STD - GV  \
        2        157.9375          166.25  ...      163.4           252.7

           TPL - SUP - PV  TPL - SUP - SV  TPL - FAM - PV  TPL - ECO  QAD - FAM - PV  \
        2           279.3           319.2           399.0     228.76           513.0

           DBL - SUP - PV +2CH  DBL - SUP - SV +2CH  DBL - FAM - PV+2CH
        2              249.375                285.0              356.25

        [1 rows x 27 columns]                                                           ,
          first date second date  Main Rate D.STD.GV  Main Rate D.STD.PV  \
        2 2023-07-04  2023-07-04               90.25                95.0

           Main Rate D.SUP.PV  Main Rate D.SUP.SV  Main Rate FAM- PV  Main Rate D.ECO  \
        2               99.75               114.0              142.5             81.7

           SGL - STD - GV  SGL - STD - PV  ...  DBL - ECO  TPL - STD - GV  \
        2        157.9375          166.25  ...      163.4           252.7

           TPL - SUP - PV  TPL - SUP - SV  TPL - FAM - PV  TPL - ECO  QAD - FAM - PV  \
        2           279.3           319.2           399.0     228.76           513.0

           DBL - SUP - PV +2CH  DBL - SUP - SV +2CH  DBL - FAM - PV+2CH
        2              249.375                285.0              356.25

        [1 rows x 27 columns]                                                           ],
       [  first date second date  Main Rate D.STD.GV  Main Rate D.STD.PV  \
        2 2023-07-12  2023-07-12               90.25                95.0

           Main Rate D.SUP.PV  Main Rate D.SUP.SV  Main Rate FAM- PV  Main Rate D.ECO  \
        2               99.75               114.0              142.5             81.7

           SGL - STD - GV  SGL - STD - PV  ...  DBL - ECO  TPL - STD - GV  \
        2        157.9375          166.25  ...      163.4           252.7

           TPL - SUP - PV  TPL - SUP - SV  TPL - FAM - PV  TPL - ECO  QAD - FAM - PV  \
        2           279.3           319.2           399.0     228.76           513.0

           DBL - SUP - PV +2CH  DBL - SUP - SV +2CH  DBL - FAM - PV+2CH
        2              249.375                285.0              356.25

        [1 rows x 27 columns]                                                           ,
          first date second date  Main Rate D.STD.GV  Main Rate D.STD.PV  \
        2 2023-07-12  2023-09-01               90.25                95.0

           Main Rate D.SUP.PV  Main Rate D.SUP.SV  Main Rate FAM- PV  Main Rate D.ECO  \
        2               99.75               114.0              142.5             81.7

           SGL - STD - GV  SGL - STD - PV  ...  DBL - ECO  TPL - STD - GV  \
        2        157.9375          166.25  ...      163.4           252.7

           TPL - SUP - PV  TPL - SUP - SV  TPL - FAM - PV  TPL - ECO  QAD - FAM - PV  \
        2           279.3           319.2           399.0     228.76           513.0

           DBL - SUP - PV +2CH  DBL - SUP - SV +2CH  DBL - FAM - PV+2CH
        2              249.375                285.0              356.25

        [1 rows x 27 columns]                                                           ,
          first date second date  Main Rate D.STD.GV  Main Rate D.STD.PV  \
        2 2023-07-12  2023-07-12               90.25                95.0

           Main Rate D.SUP.PV  Main Rate D.SUP.SV  Main Rate FAM- PV  Main Rate D.ECO  \
        2               99.75               114.0              142.5             81.7

           SGL - STD - GV  SGL - STD - PV  ...  DBL - ECO  TPL - STD - GV  \
        2        157.9375          166.25  ...      163.4           252.7

           TPL - SUP - PV  TPL - SUP - SV  TPL - FAM - PV  TPL - ECO  QAD - FAM - PV  \
        2           279.3           319.2           399.0     228.76           513.0

           DBL - SUP - PV +2CH  DBL - SUP - SV +2CH  DBL - FAM - PV+2CH
        2              249.375                285.0              356.25

        [1 rows x 27 columns]                                                           ,
          first date second date  Main Rate D.STD.GV  Main Rate D.STD.PV  \
        2 2023-07-12  2023-07-12               90.25                95.0

           Main Rate D.SUP.PV  Main Rate D.SUP.SV  Main Rate FAM- PV  Main Rate D.ECO  \
        2               99.75               114.0              142.5             81.7

           SGL - STD - GV  SGL - STD - PV  ...  DBL - ECO  TPL - STD - GV  \
        2        157.9375          166.25  ...      163.4           252.7

           TPL - SUP - PV  TPL - SUP - SV  TPL - FAM - PV  TPL - ECO  QAD - FAM - PV  \
        2           279.3           319.2           399.0     228.76           513.0

           DBL - SUP - PV +2CH  DBL - SUP - SV +2CH  DBL - FAM - PV+2CH
        2              249.375                285.0              356.25

        [1 rows x 27 columns]                                                           ,
          first date second date  Main Rate D.STD.GV  Main Rate D.STD.PV  \
        2 2023-07-12  2023-07-12               90.25                95.0

           Main Rate D.SUP.PV  Main Rate D.SUP.SV  Main Rate FAM- PV  Main Rate D.ECO  \
        2               99.75               114.0              142.5             81.7

           SGL - STD - GV  SGL - STD - PV  ...  DBL - ECO  TPL - STD - GV  \
        2        157.9375          166.25  ...      163.4           252.7

           TPL - SUP - PV  TPL - SUP - SV  TPL - FAM - PV  TPL - ECO  QAD - FAM - PV  \
        2           279.3           319.2           399.0     228.76           513.0

           DBL - SUP - PV +2CH  DBL - SUP - SV +2CH  DBL - FAM - PV+2CH
        2              249.375                285.0              356.25

        [1 rows x 27 columns]                                                           ,
          first date second date  Main Rate D.STD.GV  Main Rate D.STD.PV  \
        2 2023-07-12  2023-07-12               90.25                95.0

           Main Rate D.SUP.PV  Main Rate D.SUP.SV  Main Rate FAM- PV  Main Rate D.ECO  \
        2               99.75               114.0              142.5             81.7

           SGL - STD - GV  SGL - STD - PV  ...  DBL - ECO  TPL - STD - GV  \
        2        157.9375          166.25  ...      163.4           252.7

           TPL - SUP - PV  TPL - SUP - SV  TPL - FAM - PV  TPL - ECO  QAD - FAM - PV  \
        2           279.3           319.2           399.0     228.76           513.0

           DBL - SUP - PV +2CH  DBL - SUP - SV +2CH  DBL - FAM - PV+2CH
        2              249.375                285.0              356.25

        [1 rows x 27 columns]                                                           ],
       [  first date second date  Main Rate D.STD.GV  Main Rate D.STD.PV  \
        3 2023-07-17  2023-07-17                95.0               99.75

           Main Rate D.SUP.PV  Main Rate D.SUP.SV  Main Rate FAM- PV  Main Rate D.ECO  \
        3               104.5              118.75              150.1             85.5

           SGL - STD - GV  SGL - STD - PV  ...  DBL - ECO  TPL - STD - GV  \
        3          166.25        174.5625  ...      171.0           266.0

           TPL - SUP - PV  TPL - SUP - SV  TPL - FAM - PV  TPL - ECO  QAD - FAM - PV  \
        3           292.6           332.5          420.28      239.4          540.36

           DBL - SUP - PV +2CH  DBL - SUP - SV +2CH  DBL - FAM - PV+2CH
        3               261.25              296.875              375.25

        [1 rows x 27 columns]                                                           ,
          first date second date  Main Rate D.STD.GV  Main Rate D.STD.PV  \
        3 2023-07-17  2023-09-01                95.0               99.75

           Main Rate D.SUP.PV  Main Rate D.SUP.SV  Main Rate FAM- PV  Main Rate D.ECO  \
        3               104.5              118.75              150.1             85.5

           SGL - STD - GV  SGL - STD - PV  ...  DBL - ECO  TPL - STD - GV  \
        3          166.25        174.5625  ...      171.0           266.0

           TPL - SUP - PV  TPL - SUP - SV  TPL - FAM - PV  TPL - ECO  QAD - FAM - PV  \
        3           292.6           332.5          420.28      239.4          540.36

           DBL - SUP - PV +2CH  DBL - SUP - SV +2CH  DBL - FAM - PV+2CH
        3               261.25              296.875              375.25

        [1 rows x 27 columns]                                                           ,
          first date second date  Main Rate D.STD.GV  Main Rate D.STD.PV  \
        3 2023-07-17  2023-07-17                95.0               99.75

           Main Rate D.SUP.PV  Main Rate D.SUP.SV  Main Rate FAM- PV  Main Rate D.ECO  \
        3               104.5              118.75              150.1             85.5

           SGL - STD - GV  SGL - STD - PV  ...  DBL - ECO  TPL - STD - GV  \
        3          166.25        174.5625  ...      171.0           266.0

           TPL - SUP - PV  TPL - SUP - SV  TPL - FAM - PV  TPL - ECO  QAD - FAM - PV  \
        3           292.6           332.5          420.28      239.4          540.36

           DBL - SUP - PV +2CH  DBL - SUP - SV +2CH  DBL - FAM - PV+2CH
        3               261.25              296.875              375.25

        [1 rows x 27 columns]                                                           ,
          first date second date  Main Rate D.STD.GV  Main Rate D.STD.PV  \
        3 2023-07-17  2023-07-17                95.0               99.75

           Main Rate D.SUP.PV  Main Rate D.SUP.SV  Main Rate FAM- PV  Main Rate D.ECO  \
        3               104.5              118.75              150.1             85.5

           SGL - STD - GV  SGL - STD - PV  ...  DBL - ECO  TPL - STD - GV  \
        3          166.25        174.5625  ...      171.0           266.0

           TPL - SUP - PV  TPL - SUP - SV  TPL - FAM - PV  TPL - ECO  QAD - FAM - PV  \
        3           292.6           332.5          420.28      239.4          540.36

           DBL - SUP - PV +2CH  DBL - SUP - SV +2CH  DBL - FAM - PV+2CH
        3               261.25              296.875              375.25

        [1 rows x 27 columns]                                                           ,
          first date second date  Main Rate D.STD.GV  Main Rate D.STD.PV  \
        3 2023-07-17  2023-07-17                95.0               99.75

           Main Rate D.SUP.PV  Main Rate D.SUP.SV  Main Rate FAM- PV  Main Rate D.ECO  \
        3               104.5              118.75              150.1             85.5

           SGL - STD - GV  SGL - STD - PV  ...  DBL - ECO  TPL - STD - GV  \
        3          166.25        174.5625  ...      171.0           266.0


In [ ]:
def append_and_pad(original_array, new_array):
    if original_array.ndim == 1:
        original_array = [original_array]
    # Find the maximum length between the two arrays
    max_length = max(len(original_array[0]), len(new_array))
    
    # Pad both arrays with zeros to match the maximum length
    original_array_padded = np.pad(original_array, ((0, 0), (0, max_length - len(original_array[0]))), 'constant')
    new_array_padded = np.pad(new_array, (0, max_length - len(new_array)), 'constant')
    
    # Stack the two arrays vertically
    result = np.vstack((original_array_padded, new_array_padded))
    
    return result

In [162]:
def calculate_total_price(statment,Spo_dict):
    end_date_np = np.array(Spo_dict['end_date'], dtype='datetime64').reshape(-1,1)
    start_date_np = np.array(Spo_dict['start_date'], dtype='datetime64').reshape(-1,1)
    
    result = np.vectorize(date_between)(statment['Res_date'],start_date_np,end_date_np).T
    
    invoices = np.array(list(pd.read_excel(file_path,sheet_name= Spo_dict['name']).values()))
    
    dict_of_rows = np.array(statment.to_dict(orient='records'))
    
    x = np.vectorize(invoice_optimizer)(dict_of_rows.reshape(-1,1),invoices)

(array([[0, 0, 0, 4, 4, 4],
       [0, 0, 0, 3, 3, 3],
       [0, 0, 0, 3, 3, 3],
       [0, 0, 0, 5, 5, 5]]), array([[  0,   0,   0, 190, 190, 190],
       [  0,   0,   0, 163, 163, 163],
       [  0,   0,   0, 180, 180, 180],
       [  0,   0,   0, 420, 420, 420]]), array([[Timestamp('2023-07-15 00:00:00'),
        Timestamp('2023-09-01 00:00:00'),
        Timestamp('2023-07-15 00:00:00'),
        Timestamp('2023-07-15 00:00:00'),
        Timestamp('2023-07-15 00:00:00'),
        Timestamp('2023-07-15 00:00:00')],
       [Timestamp('2023-07-04 00:00:00'),
        Timestamp('2023-09-01 00:00:00'),
        Timestamp('2023-07-04 00:00:00'),
        Timestamp('2023-07-04 00:00:00'),
        Timestamp('2023-07-04 00:00:00'),
        Timestamp('2023-07-04 00:00:00')],
       [Timestamp('2023-07-12 00:00:00'),
        Timestamp('2023-09-01 00:00:00'),
        Timestamp('2023-07-12 00:00:00'),
        Timestamp('2023-07-12 00:00:00'),
        Timestamp('2023-07-12 00:00:00'),
        Timestamp('2023-07-12 00:00:00')],
       [Timestamp('2023-07-17 00:00:00'),
        Timestamp('2023-09-01 00:00:00'),
        Timestamp('2023-07-17 00:00:00'),
        Timestamp('2023-07-17 00:00:00'),
        Timestamp('2023-07-17 00:00:00'),
        Timestamp('2023-07-17 00:00:00')]], dtype=object), array([[Timestamp('2023-06-30 00:00:00'),
        Timestamp('2023-07-18 00:00:00'),
        Timestamp('2023-06-30 00:00:00'),
        Timestamp('2023-07-18 00:00:00'),
        Timestamp('2023-07-18 00:00:00'),
        Timestamp('2023-07-18 00:00:00')],
       [Timestamp('2023-06-30 00:00:00'),
        Timestamp('2023-07-06 00:00:00'),
        Timestamp('2023-06-30 00:00:00'),
        Timestamp('2023-07-06 00:00:00'),
        Timestamp('2023-07-06 00:00:00'),
        Timestamp('2023-07-06 00:00:00')],
       [Timestamp('2023-06-30 00:00:00'),
        Timestamp('2023-07-14 00:00:00'),
        Timestamp('2023-06-30 00:00:00'),
        Timestamp('2023-07-14 00:00:00'),
        Timestamp('2023-07-14 00:00:00'),
        Timestamp('2023-07-14 00:00:00')],
       [Timestamp('2023-06-30 00:00:00'),
        Timestamp('2023-07-21 00:00:00'),
        Timestamp('2023-06-30 00:00:00'),
        Timestamp('2023-07-21 00:00:00'),
        Timestamp('2023-07-21 00:00:00'),
        Timestamp('2023-07-21 00:00:00')]], dtype=object), array([[ True,  True,  True, False, False, False],
       [ True,  True,  True, False, False, False],
       [ True,  True,  True, False, False, False],
       [ True,  True,  True, False, False, False]]))